<?php
/**
 * Created by PhpStorm.
 * User: Cliente
 * Date: 25/08/2018
 * Time: 11:26
 */

$form = $this->form;
$fieldset = $form->get('certification');

$title = $fieldset->get('title');
$title->setAttribute('class', 'form-control');
$title->setAttribute('placeholder', 'Certification title');

$text = $fieldset->get('text');
$text->setAttribute('class', 'form-control');
$text->setAttribute('placeholder', 'Certification content');

$submit = $form->get('submit');
$submit->setValue($this->submitLabel);
$submit->setAttribute('class', 'btn btn-primary');

$form->prepare();

echo $this->form()->openTag($form);
?>

<fieldset>
    <div class="form-group">
        <?= $this->formLabel($title) ?>
        <?= $this->formElement($title) ?>
        <?= $this->formElementErrors()->render($title, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($text) ?>
        <?= $this->formElement($text) ?>
        <?= $this->formElementErrors()->render($text, ['class' => 'help-block']) ?>
    </div>
</fieldset>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($fieldset->get('id'));
echo $this->form()->closeTag();
